# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/constraints.xdc

# IP: ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# IP: ip/multiplier/multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: ip/clk_divider/clk_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_divider || ORIG_REF_NAME==clk_divider} -quiet] -quiet
