# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.cache/wt [current_project]
set_property parent.project_path /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog [current_fileset]
read_verilog -library xil_defaultlib {
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/BRAM2BELoad.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/ClockInverter.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/Counter.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/FIFO1.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/FIFO2.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/FIFO20.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/FIFOL1.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/MakeClock.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/MakeReset0.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/MakeResetA.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/RegFile.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/ResetEither.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/SizedFIFO.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/SyncFIFO1.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/SyncHandshake.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/SyncRegister.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/SyncReset0.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/SyncResetA.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/UngatedClockMux.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkSoc.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkalu.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkcsr.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkcsrfile.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkeclass.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkeclass_axi4lite.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkgpio.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mki2c.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkmixed_cluster.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkmuldiv.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkplic.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkpwm.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkpwm_cluster.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkrestoring_div.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkriscv.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkriscvDebug013.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkspi.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkspi_cluster.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkstage1.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkstage2.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkstage3.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkuart.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkuart_cluster.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/mkxilinxdtm.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/module_address_valid.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/module_chk_interrupt.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/module_decoder_func_32.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/module_fn_alu.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/module_fn_decompress.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/verilog/module_singlestep.v
  /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_top.v
}
read_ip -quiet /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

read_ip -quiet /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/multiplier/multiplier.xci
set_property used_in_implementation false [get_files -all /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/multiplier/multiplier_ooc.xdc]

read_ip -quiet /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/clk_divider/clk_divider.xci
set_property used_in_implementation false [get_files -all /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/clk_divider/clk_divider_board.xdc]
set_property used_in_implementation false [get_files -all /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/clk_divider/clk_divider.xdc]
set_property used_in_implementation false [get_files -all /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/fpga_project/e-class/e-class.srcs/sources_1/ip/clk_divider/clk_divider_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/constraints.xdc
set_property used_in_implementation false [get_files /home/sreh/shakti/shakti-soc/fpga/boards/artya7-35t/e-class/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga_top -part xc7a35ticsg324-1L  -verilog_define BSV_RESET_FIFO_HEAD -verilog_define BSV_RESET_FIFO_ARRAY -verilog_define BSV_ASYNC_RESET -verilog_define JTAG_BSCAN2E


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
create_report "core_synth_1_synth_report_utilization_0" "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
